package dev.fallingcloud.slate.chat.client;

import dev.fallingcloud.slate.chat.SlateChat;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.MutableComponent;
import net.minecraft.network.chat.Style;
import net.minecraft.resources.ResourceLocation;
import org.jetbrains.annotations.Nullable;

/**
 * The pixel emote set: {@code :name:} in text maps to a private-use glyph in the {@code slate_chat:emotes}
 * bitmap font ({@code assets/slate_chat/font/emotes.json}, sheet generated by {@code tools/emotes.py}).
 * Substitution happens on the RENDERED component only; the wire text keeps {@code :smile:} so unmodded
 * players read it as-is.
 */
public final class Emotes {

    public static final ResourceLocation FONT = SlateChat.id("emotes");
    /** First code point; emote i is {@code BASE + i}. Keep in sync with tools/emotes.py. */
    public static final int BASE = 0xE100;

    /** Order = sheet order = code point order. */
    public static final List<String> NAMES = List.of(
        "smile", "grin", "laugh", "wink", "sad", "cry", "angry", "surprised",
        "thinking", "cool", "heart", "broken_heart", "thumbs_up", "thumbs_down", "fire", "skull",
        "wave", "clap", "eyes", "sparkles", "sword", "pickaxe", "creeper", "diamond");

    private static final Pattern TOKEN = Pattern.compile(":([a-z_]{2,16}):");

    public static int indexOf(final String name) {
        return NAMES.indexOf(name);
    }

    /** The one-character string for an emote, or null for unknown names. */
    @Nullable
    public static String glyph(final String name) {
        final int i = indexOf(name);
        return i < 0 ? null : new String(Character.toChars(BASE + i));
    }

    /** The glyph as a renderable component (white so the sheet's own colours show). */
    public static MutableComponent component(final String name) {
        final String g = glyph(name);
        return Component.literal(g == null ? ":" + name + ":" : g).withStyle(Style.EMPTY.withFont(FONT).withColor(0xFFFFFF));
    }

    /** What the picker inserts into the input. */
    public static String token(final String name) {
        return ":" + name + ":";
    }

    /** Replaces known {@code :name:} tokens inside one styled text segment. */
    static MutableComponent rewriteSegment(final String text, final Style style, final MutableComponent into) {
        final Matcher m = TOKEN.matcher(text);
        int last = 0;
        while (m.find()) {
            final String g = glyph(m.group(1));
            if (g == null) continue;
            if (m.start() > last) into.append(Component.literal(text.substring(last, m.start())).withStyle(style));
            into.append(Component.literal(g).withStyle(style.withFont(FONT).withColor(0xFFFFFF)));
            last = m.end();
        }
        if (last < text.length()) into.append(Component.literal(text.substring(last)).withStyle(style));
        return into;
    }

    public static boolean containsToken(final String text) {
        if (text == null || text.indexOf(':') < 0) return false;
        final Matcher m = TOKEN.matcher(text);
        while (m.find()) if (indexOf(m.group(1)) >= 0) return true;
        return false;
    }

    private Emotes() {}
}
