#!/usr/bin/env python3
"""
Slate mod icons (the 64x64 PNG each loader shows in its mod list).

Every icon is a 32x32 ASCII motif scaled 2x (nearest) over the dark-skin background
(#161615) with a 2 px pixel-stepped border (#33332F); the corners outside the border are
transparent. Letters in the motifs:
    '.'  background shows through
    'a'  accent            #D9805E   (DESIGN.md dark palette accent)
    'A'  accent, lighter             (the "lit" top edge of the slate tile, the door)
    'd'  accent, darker              (the tile's bottom edge)
    'm'  muted grey                  (slider tracks)
    't'  text                #ECEAE4

Outputs one file per module:
    common/<module>/src/main/resources/assets/<modid>/icon.png

Usage: python tools/modicons.py
"""
from __future__ import annotations

import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

GRID = 32
SCALE = 2
CORNER = 3          # stepped corner: 3 px cut in the 32 grid -> steps of 2 px at 64
BORDER = 1          # 1 px in the 32 grid -> 2 px at 64

BG = (0x16, 0x16, 0x15, 255)
BORDER_COLOR = (0x33, 0x33, 0x2F, 255)
PALETTE = {
    "a": (0xD9, 0x80, 0x5E, 255),
    "A": (0xE6, 0xA5, 0x8B, 255),
    "d": (0xA8, 0x62, 0x48, 255),
    "m": (0x8A, 0x88, 0x80, 255),
    "t": (0xEC, 0xEA, 0xE4, 255),
}

# module dir -> (mod id, motif)
ICONS: dict[str, tuple[str, str]] = {}


def motif(module: str, modid: str, art: str) -> None:
    rows = art.strip("\n").splitlines()
    if len(rows) != GRID:
        raise SystemExit(f"{modid}: expected {GRID} rows, got {len(rows)}")
    for i, row in enumerate(rows):
        if len(row) != GRID:
            raise SystemExit(f"{modid}: row {i} has {len(row)} chars: {row!r}")
        bad = set(row) - set(".") - set(PALETTE)
        if bad:
            raise SystemExit(f"{modid}: row {i} has invalid chars {sorted(bad)}")
    ICONS[module] = (modid, "\n".join(rows))


def inside(x: int, y: int, x0: int, y0: int, x1: int, y1: int, cut: int) -> bool:
    """Point inside the box [x0,x1]x[y0,y1] whose corners are cut on a diagonal of `cut` px."""
    if x < x0 or x > x1 or y < y0 or y > y1:
        return False
    dx = min(x - x0, x1 - x)
    dy = min(y - y0, y1 - y)
    return dx + dy >= cut


def render(art: str) -> Image.Image:
    im = Image.new("RGBA", (GRID, GRID), (0, 0, 0, 0))
    px = im.load()
    rows = art.splitlines()
    for y in range(GRID):
        for x in range(GRID):
            if not inside(x, y, 0, 0, GRID - 1, GRID - 1, CORNER):
                continue  # transparent rounded corner
            if not inside(x, y, BORDER, BORDER, GRID - 1 - BORDER, GRID - 1 - BORDER, CORNER - 1):
                px[x, y] = BORDER_COLOR
                continue
            ch = rows[y][x]
            px[x, y] = PALETTE[ch] if ch in PALETTE else BG
    return im.resize((GRID * SCALE, GRID * SCALE), Image.NEAREST)


# Core: the suite logo - a slate tile with a lit top edge and a shadowed bottom edge.
motif("core", "slate", """
................................
................................
................................
................................
................................
................................
.........AAAAAAAAAAAAAA.........
........AAAAAAAAAAAAAAAA........
.......AAAAAAAAAAAAAAAAAA.......
......AAAAAAAAAAAAAAAAAAAA......
......aaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaaaa......
.......dddddddddddddddddd.......
........dddddddddddddddd........
.........dddddddddddddd.........
................................
................................
................................
................................
................................
................................
""")

# Menu: home - a house with a chimney and a lit door.
motif("menu", "slate_menu", """
................................
................................
................................
................................
................................
...............aa...............
..............aaaa..............
.............aaaaaa..aa.........
............aaaaaaaa.aa.........
...........aaaaaaaaaaaa.........
..........aaaaaaaaaaaaa.........
.........aaaaaaaaaaaaaa.........
........aaaaaaaaaaaaaaaa........
.......aaaaaaaaaaaaaaaaaa.......
......aaaaaaaaaaaaaaaaaaaa......
.....aaaaaaaaaaaaaaaaaaaaaa.....
....aaaaaaaaaaaaaaaaaaaaaaaa....
....aaaaaaaaaaaaaaaaaaaaaaaa....
.......aaaaaaaaaaaaaaaaaa.......
.......aaaaaaaaaaaaaaaaaa.......
.......aaaaaaAAAAAAaaaaaa.......
.......aaaaaaAAAAAAaaaaaa.......
.......aaaaaaAAAAAAaaaaaa.......
.......aaaaaaAAAAAAaaaaaa.......
.......aaaaaaAAAAAAaaaaaa.......
.......aaaaaaAAAAAAaaaaaa.......
.......aaaaaaAAAAAAaaaaaa.......
.......aaaaaaAAAAAAaaaaaa.......
................................
................................
................................
................................
""")

# Multiplayer: two heads side by side.
motif("multiplayer", "slate_multiplayer", """
................................
................................
................................
................................
................................
................................
.......aaaa..........AAAA.......
......aaaaaa........AAAAAA......
......aaaaaa........AAAAAA......
......aaaaaa........AAAAAA......
......aaaaaa........AAAAAA......
.......aaaa..........AAAA.......
................................
................................
......aaaaaa........AAAAAA......
.....aaaaaaaa......AAAAAAAA.....
....aaaaaaaaaa....AAAAAAAAAA....
....aaaaaaaaaa....AAAAAAAAAA....
....aaaaaaaaaa....AAAAAAAAAA....
....aaaaaaaaaa....AAAAAAAAAA....
....aaaaaaaaaa....AAAAAAAAAA....
....aaaaaaaaaa....AAAAAAAAAA....
....aaaaaaaaaa....AAAAAAAAAA....
....aaaaaaaaaa....AAAAAAAAAA....
....aaaaaaaaaa....AAAAAAAAAA....
....aaaaaaaaaa....AAAAAAAAAA....
................................
................................
................................
................................
................................
................................
""")

# Chat: a speech bubble with a typing ellipsis.
motif("chat", "slate_chat", """
................................
................................
................................
................................
................................
.......aaaaaaaaaaaaaaaaaa.......
......aaaaaaaaaaaaaaaaaaaa......
.....aaaaaaaaaaaaaaaaaaaaaa.....
....aaaaaaaaaaaaaaaaaaaaaaaa....
....aaaaaaaaaaaaaaaaaaaaaaaa....
....aaaaaaaaaaaaaaaaaaaaaaaa....
....aaaaaaaaaaaaaaaaaaaaaaaa....
....aaaaa...aa...aa...aaaaaa....
....aaaaa...aa...aa...aaaaaa....
....aaaaa...aa...aa...aaaaaa....
....aaaaaaaaaaaaaaaaaaaaaaaa....
....aaaaaaaaaaaaaaaaaaaaaaaa....
....aaaaaaaaaaaaaaaaaaaaaaaa....
....aaaaaaaaaaaaaaaaaaaaaaaa....
....aaaaaaaaaaaaaaaaaaaaaaaa....
.....aaaaaaaaaaaaaaaaaaaaaa.....
......aaaaaaaaaaaaaaaaaaaa......
.......aaaaaaaaaaaaaaaaaa.......
........aaaaa...................
........aaaa....................
........aaa.....................
........aa......................
................................
................................
................................
................................
................................
""")

# Config: three sliders.
motif("config", "slate_config", """
................................
................................
................................
................................
................................
................................
...................aa...........
..................aaaa..........
....mmmmmmmmmmmmmmaaaammmmmm....
....mmmmmmmmmmmmmmaaaammmmmm....
..................aaaa..........
...................aa...........
................................
..........aa....................
.........aaaa...................
....mmmmmaaaammmmmmmmmmmmmmm....
....mmmmmaaaammmmmmmmmmmmmmm....
.........aaaa...................
..........aa....................
................................
.......................aa.......
......................aaaa......
....mmmmmmmmmmmmmmmmmmaaaamm....
....mmmmmmmmmmmmmmmmmmaaaamm....
......................aaaa......
.......................aa.......
................................
................................
................................
................................
................................
................................
""")


def main() -> int:
    for module, (modid, art) in ICONS.items():
        path = os.path.join(ROOT, "common", module, "src", "main", "resources", "assets", modid, "icon.png")
        os.makedirs(os.path.dirname(path), exist_ok=True)
        render(art).save(path, optimize=True)
        print("wrote", os.path.relpath(path, ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
